### ISSUE TITLE
pod installation failed

### ISSUE THREAD

**Issue by phoenisis** [fouquet/RFAboutView#3]
RFAboutView failed to install via cocoapods using : pod "RFAboutView", '~> 1.0.3'

```
pod install print out : [!] Unable to satisfy the following requirements:

- `RFAboutView (~> 1.0.3)` required by `Podfile` 
```

**Comment by fouquet** [comment]
The problem must be on your end, it works fine here:

```
$ echo "pod 'RFAboutView', '~> 1.0.3'" > Podfile
$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing RFAboutView (1.0.3)
Generating Pods project
Integrating client project
Sending stats
```

**Comment by fabiosoft** [comment]
@phoenisis Update your Deployment Target to something >= of iOS8 and everything will work like a charm... (workaround i found) ...I think the limit is given by UIVisualEffects API

**Comment by sahil263** [comment]
@fouquet Not working for me either...

![screen shot 2015-09-27 at 9 03 05 am](https://cloud.githubusercontent.com/assets/4958184/10121038/c913bdb4-64f6-11e5-8c83-91c7f1999516.png)

I am on Xcode v7.0 and Development Target is set to >= iOS 8.

**Comment by fouquet** [comment]
Unfortunately I'm still unable to reproduce this. It's working just fine for me, on two different Macs.
